[SASS-382] update test dependency
hmrc/income-tax-dividends pull request #13
Opened 2021-03-01 12:07 UTC by dnyuar

2021-03-01 12:08 UTC, dnyuar commented
SASS-382 reopened to update scalatest dependency

2021-03-02 10:26 UTC, robert-webb-hmrc requested changes
can we get the following warns addressed please?
<img width="1649" alt="Screenshot 2021-03-02 at 10 11 03" src="https://user-images.githubusercontent.com/28566263/109634965-bf72e200-7b41-11eb-9194-d6908fe75d3d.png">

2021-03-02 10:36 UTC, dnyuar commented
Unused imports have been removed

2021-03-02 11:18 UTC, robert-webb-hmrc approved these changes

2021-03-02 11:18 UTC, merged