SASS-48
hmrc/income-tax-dividends pull request #2
Opened 2020-10-27 23:55 UTC by TheDeadlyPianist

2020-10-29 14:24 UTC, juamalBlackman requested changes

2020-10-29 14:24 UTC, juamalBlackman commented on app/common/SessionValues.scala
> +}
Not currently used at the moment

2020-10-29 14:24 UTC, juamalBlackman commented on build.sbt
>    .settings(
.settings(coverageSettings: _*) is missing and is coverage staying at 95 or going to 90

2020-10-29 14:24 UTC, juamalBlackman commented on app/models/User.scala
> +}
needs to be tested 
<img width="1340" alt="Screenshot 2020-10-29 at 2 19 18 pm" src="https://user-images.githubusercontent.com/63247344/97586210-e84b6500-19f1-11eb-80be-441d09b21d69.png">

2020-10-29 14:28 UTC, juamalBlackman commented
might be worth also disabling Junit plugins to prevent unstable builds 
  .disablePlugins(sbt.plugins.JUnitXmlReportPlugin)
  .disablePlugins(JUnitXmlReportPlugin)

2020-11-03 15:27 UTC, matt712 reviewed
There are some old dependencies in the AppDependencies.scala file.  https://catalogue.tax.service.gov.uk/service/income-tax-dividends

2020-11-04 10:29 UTC, matt712 approved these changes

2020-11-04 10:30 UTC, merged